services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web_server
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./public:/public

  pdf_maker:
    build:
      context: .
      dockerfile: Dockerfile.pdf_maker
    tty: true
    environment:
      - PORT=${PORT}
      - SERVICE_NAME=${SERVICE_NAME}

  http-client:
    image: badouralix/curl-jq
    tty: true